name: Test
on:
  pull_request:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - 
        name: Test
        run: go test
